"""场景模板种子数据 — 角色化版本

角色分类：
  property_manager — 物业项目经理（管保安/保洁，对接甲方业主）
  decoration_boss  — 装修公司老板（管工头/工人，对接客户供应商）
  general          — 两个角色都适用（家庭 + 朋友圈场景）
"""

import json

SCENARIOS_SEED = [
    # ============ 职场A：物业项目经理 ============
    {
        "category": "workplace",
        "sub_type": "pm_client_extra_work",
        "title": "甲方要求加活不加钱",
        "role_brief": "甲方代表，验收时突然提出要在原合同范围外加几项工作，态度理所当然，暗示不做就不签字",
        "tension_brief": "做了亏钱亏人，不做对方卡你付款——还要把这个关系维护好",
        "user_goal_brief": "争取补偿或合理边界，不撕破脸皮，保住回款",
        "primary_skills": ["B1", "E1", "L2"],
        "difficulty": 4,
        "applicable_roles": ["property_manager"],
        "generation_prompt": "生成甲方在验收现场要求增加合同外工作的开场，语气带着理所当然和隐性威胁",
    },
    {
        "category": "workplace",
        "sub_type": "pm_client_overdue_payment",
        "title": "甲方拖款已3个月",
        "role_brief": "甲方财务或项目负责人，每次催款都推说走流程、领导出差、资金紧张，态度客气但就是不付",
        "tension_brief": "关系不能搞僵还要继续合作，但再不催就真烂账了",
        "user_goal_brief": "逼出一个明确的打款时间节点，同时保全双方脸面",
        "primary_skills": ["B1", "R1", "E1"],
        "difficulty": 4,
        "applicable_roles": ["property_manager"],
        "generation_prompt": "生成甲方财务接到催款电话后，用'正在走审批'应付的场景开场",
    },
    {
        "category": "workplace",
        "sub_type": "pm_guard_lazy",
        "title": "保安懒散被业主投诉",
        "role_brief": "被投诉的保安小王，已经在这个岗位三年，觉得自己经验丰富，认为你是在挑他刺",
        "tension_brief": "直接批评他会对抗，但不处理投诉会传到甲方那里",
        "user_goal_brief": "让他认识到问题严重性并接受整改，同时稳住他不辞职",
        "primary_skills": ["L1", "E1", "EM1"],
        "difficulty": 3,
        "applicable_roles": ["property_manager"],
        "generation_prompt": "生成保安小王被叫来谈话，带着委屈和防御心理的开场",
    },
    {
        "category": "workplace",
        "sub_type": "pm_cleaner_passive",
        "title": "保洁消极怠工影响士气",
        "role_brief": "做了五年的保洁大姐，最近因为工资没涨开始阳奉阴违，速度慢质量差，还会带其他人一起抱怨",
        "tension_brief": "她走了一时找不到人，但她待着也在拖整体水平",
        "user_goal_brief": "搞清楚真实诉求，找到解决方案，稳住队伍",
        "primary_skills": ["L1", "EM1", "E2"],
        "difficulty": 3,
        "applicable_roles": ["property_manager"],
        "generation_prompt": "生成保洁大姐被约谈时，先诉苦工资低再说自己已经很努力的开场",
    },
    {
        "category": "workplace",
        "sub_type": "pm_owner_complaint",
        "title": "业主当面投诉物业服务",
        "role_brief": "长期对物业不满的业主，今天堵在门口激动地投诉停车管理乱、保洁卫生差，要见负责人",
        "tension_brief": "当众吵架会扩散影响，但不管用用户会去12345投诉",
        "user_goal_brief": "当场平息情绪，给出承诺，避免事态扩大",
        "primary_skills": ["EM1", "L1", "R1"],
        "difficulty": 4,
        "applicable_roles": ["property_manager"],
        "generation_prompt": "生成业主在物业大厅当面激动投诉、声音越来越大的开场",
    },
    {
        "category": "workplace",
        "sub_type": "pm_budget_cut",
        "title": "甲方突然要砍预算20%",
        "role_brief": "甲方领导，开季度会时突然宣布要压缩物业管理费，态度是这是公司决定，不讨论",
        "tension_brief": "砍了20%实际运营根本跑不动，但正面刚又显得不识好歹",
        "user_goal_brief": "用数据和逻辑争取合理预算，至少保住核心项目不被砍",
        "primary_skills": ["L2", "E1", "B1"],
        "difficulty": 5,
        "applicable_roles": ["property_manager"],
        "generation_prompt": "生成甲方领导在会议上宣布削减预算，强调这是既定决定的开场",
    },
    {
        "category": "workplace",
        "sub_type": "pm_mediate_owner_conflict",
        "title": "业主之间车位纠纷要你仲裁",
        "role_brief": "两个业主——A长期占着B的固定车位，B今天堵在楼道不让A走，两人都要你来评理",
        "tension_brief": "帮任何一方都得罪另一方，还不能拖着不解决",
        "user_goal_brief": "当场给出方案让两人都能接受，不激化矛盾",
        "primary_skills": ["R1", "EM1", "B1"],
        "difficulty": 4,
        "applicable_roles": ["property_manager"],
        "generation_prompt": "生成两个业主同时跟你理论、各说各有理的开场",
    },
    {
        "category": "workplace",
        "sub_type": "pm_client_scheme_change",
        "title": "甲方验收前临时改方案",
        "role_brief": "甲方项目经理，在验收前两天突然说要调整一个区域的管理方案，理由是'领导要求'，没有书面依据",
        "tension_brief": "改了要加钱加人，不改甲方不满意签字拖",
        "user_goal_brief": "搞清楚改的范围，签补充协议，不白干活",
        "primary_skills": ["E1", "B1", "L2"],
        "difficulty": 4,
        "applicable_roles": ["property_manager"],
        "generation_prompt": "生成甲方项目经理提出临时变更要求、措辞含糊的开场",
    },
    {
        "category": "workplace",
        "sub_type": "pm_drinking_pressure",
        "title": "应酬被甲方强行敬酒",
        "role_brief": "甲方陪同领导，酒桌上以'大家都喝了就你不喝显得见外'为由反复敬酒，场面有点僵",
        "tension_brief": "喝了身体吃不消，不喝被说没诚意，关系还要维护",
        "user_goal_brief": "优雅拒绝不失礼，找到既照顾双方脸面又不伤身体的方式",
        "primary_skills": ["H1", "B1", "R1"],
        "difficulty": 3,
        "applicable_roles": ["property_manager"],
        "generation_prompt": "生成酒桌上甲方领导执意敬酒、旁边人也在起哄的开场",
    },

    # ============ 职场B：装修公司老板 ============
    {
        "category": "workplace",
        "sub_type": "deco_client_redesign",
        "title": "客户反复改设计不加钱",
        "role_brief": "签了全包合同的客户，已经让你改了第三版设计稿，每次改完还有新想法，理由是'就微调一下'",
        "tension_brief": "改一次就亏一次工时，拒绝又怕客户差评，还在施工中途",
        "user_goal_brief": "温和但坚定地把边界说清楚，启动变更费收费机制",
        "primary_skills": ["B1", "E1", "R1"],
        "difficulty": 4,
        "applicable_roles": ["decoration_boss"],
        "generation_prompt": "生成客户发来第三版修改意见、依然认为是小改动的开场",
    },
    {
        "category": "workplace",
        "sub_type": "deco_client_final_payment",
        "title": "验收时客户挑刺拒付尾款",
        "role_brief": "验收当天的客户，绕着房间找问题，说墙角缝隙大了、颜色不对、地板有声音，要求全部返工再谈付款",
        "tension_brief": "有些确实是正常施工误差，但有些客户明显在找借口拖尾款",
        "user_goal_brief": "专业回应每个问题，分清合理要求和借口，争取尽快收尾款",
        "primary_skills": ["L2", "E1", "B1"],
        "difficulty": 5,
        "applicable_roles": ["decoration_boss"],
        "generation_prompt": "生成客户在验收时挑出一堆问题、强调付完尾款才算验收的开场",
    },
    {
        "category": "workplace",
        "sub_type": "deco_foreman_extra_money",
        "title": "工头工期延误还要加钱",
        "role_brief": "合作多年的工头老张，工期已经拖了10天，现在说材料涨价人工贵了，要额外加3万才继续干",
        "tension_brief": "换人更延误客户那边压力更大，不加钱工头甩手不干",
        "user_goal_brief": "谈出一个折中方案，不白给钱，也稳住工头把活收完",
        "primary_skills": ["B1", "L1", "E1"],
        "difficulty": 4,
        "applicable_roles": ["decoration_boss"],
        "generation_prompt": "生成工头老张拿着账单来你办公室，边算钱边说自己也亏了的开场",
    },
    {
        "category": "workplace",
        "sub_type": "deco_workers_fight",
        "title": "工地工人打架影响工期",
        "role_brief": "工地上两组工人——瓦工和木工——因为施工顺序问题起了冲突，有人动手，现在都停工等你来处理",
        "tension_brief": "不处理好就停工，但哪边说重了都可能有人甩手走人",
        "user_goal_brief": "当场平息，划清责任，让两组都回去干活",
        "primary_skills": ["EM1", "R1", "L1"],
        "difficulty": 4,
        "applicable_roles": ["decoration_boss"],
        "generation_prompt": "生成工地两组工人都在向你诉说对方过错、场面混乱的开场",
    },
    {
        "category": "workplace",
        "sub_type": "deco_supplier_price_hike",
        "title": "供应商突然涨价10%",
        "role_brief": "长期合作的主材供应商，微信发来通知说原材料涨价，下周起所有订单涨10%，已签合同也要补差价",
        "tension_brief": "已签给客户的价格改不了，吃下去直接亏，但找新供应商也来不及",
        "user_goal_brief": "谈出保价方案或分摊机制，不能全部自己扛",
        "primary_skills": ["B1", "E1", "L2"],
        "difficulty": 4,
        "applicable_roles": ["decoration_boss"],
        "generation_prompt": "生成供应商发来涨价通知、强调成本压力的开场",
    },
    {
        "category": "workplace",
        "sub_type": "deco_client_night_msg",
        "title": "客户深夜连发消息催进度",
        "role_brief": "焦虑型客户，晚上11点开始在微信群发消息，说明天要来看进度、要求解释为什么还没贴砖，@了你和工头",
        "tension_brief": "睡着了没回会被认为不负责，回了又给自己立了随时待命的规矩",
        "user_goal_brief": "回应关切但设定沟通边界，明确进度节点，不让深夜骚扰成常态",
        "primary_skills": ["B1", "R1", "E1"],
        "difficulty": 3,
        "applicable_roles": ["decoration_boss"],
        "generation_prompt": "生成客户深夜在微信群发消息连问几个问题的开场",
    },
    {
        "category": "workplace",
        "sub_type": "deco_complaint_12345",
        "title": "接到12345转来的投诉",
        "role_brief": "当地市场监管部门工作人员，转达了某客户的投诉（说你们施工噪音扰民/材料以次充好），要求你在3个工作日内书面回复",
        "tension_brief": "这个客户确实有纠纷在处理，但部门介入升级了压力",
        "user_goal_brief": "妥善处理投诉，避免被列入黑名单，同时推动客户纠纷解决",
        "primary_skills": ["L2", "E1", "R1"],
        "difficulty": 3,
        "applicable_roles": ["decoration_boss"],
        "generation_prompt": "生成监管部门工作人员电话通知投诉情况、语气公事公办的开场",
    },
    {
        "category": "workplace",
        "sub_type": "deco_old_client_discount",
        "title": "老客户要求熟人价折扣",
        "role_brief": "三年前装过房的老客户，帮你介绍了两个新客户，现在自己想装第二套房，理由充分地要求8折",
        "tension_brief": "8折直接亏本，但老客户介绍过生意，驳了他面子也影响口碑",
        "user_goal_brief": "感谢老客户的同时，婉拒过分折扣，给出一个双方都能接受的方案",
        "primary_skills": ["H1", "B1", "R1"],
        "difficulty": 3,
        "applicable_roles": ["decoration_boss"],
        "generation_prompt": "生成老客户理直气壮地要8折、历数自己之前贡献的开场",
    },

    # ============ 家庭：两个角色都适用 ============
    {
        "category": "family",
        "sub_type": "teen_son_backtalk",
        "title": "14岁儿子顶嘴不服管",
        "role_brief": "你14岁的儿子，因为被要求少打游戏多看书，开始顶嘴，说'你也不看书，凭什么管我'",
        "tension_brief": "大声压制他会让他更对抗，无视他又助长这种态度",
        "user_goal_brief": "不硬碰硬，把对话引向真正的问题——他为什么抵触学习",
        "primary_skills": ["L1", "EM1", "E2"],
        "difficulty": 4,
        "applicable_roles": ["general"],
        "generation_prompt": "生成14岁少年被要求放下手机、用反问句顶嘴的开场",
    },
    {
        "category": "family",
        "sub_type": "teen_son_study_useless",
        "title": "儿子说读书没什么用",
        "role_brief": "你14岁的儿子，看了某个视频说某网红学历低但收入高，现在跟你认真地讨论读书到底有没有用",
        "tension_brief": "用老一套大道理他不信，但真的允许他这么想又危险",
        "user_goal_brief": "认真回应而不是敷衍，帮他建立更有深度的思考框架",
        "primary_skills": ["L1", "H1", "E2"],
        "difficulty": 4,
        "applicable_roles": ["general"],
        "generation_prompt": "生成14岁儿子认真提出'读书无用论'、并举了真实例子的开场",
    },
    {
        "category": "family",
        "sub_type": "teen_son_gaming_addict",
        "title": "儿子熬夜打游戏到凌晨2点",
        "role_brief": "你14岁的儿子，被你发现又熬夜打游戏，承认了但辩解说反正明天不上课、他能控制自己",
        "tension_brief": "骂了当晚收一下，明天继续；讲道理他右耳进左耳出",
        "user_goal_brief": "找到让他自己认识到问题的方式，而不只是一次性说服",
        "primary_skills": ["EM1", "L1", "E2"],
        "difficulty": 3,
        "applicable_roles": ["general"],
        "generation_prompt": "生成凌晨被发现打游戏的儿子，不太在乎地辩解自己能控制的开场",
    },
    {
        "category": "family",
        "sub_type": "daughter_social_excluded",
        "title": "12岁女儿说被同学孤立",
        "role_brief": "你12岁的女儿，哭着告诉你班里几个好朋友突然不理她了，她不知道为什么，觉得自己做错了什么",
        "tension_brief": "直接给建议容易让她觉得不被理解，光安慰又没用",
        "user_goal_brief": "先接住她的情绪，再帮她梳理发生了什么，找到她能做的第一步",
        "primary_skills": ["EM2", "L1", "E2"],
        "difficulty": 3,
        "applicable_roles": ["general"],
        "generation_prompt": "生成12岁女儿哭泣着说被好朋友冷落、不知道原因的开场",
    },
    {
        "category": "family",
        "sub_type": "daughter_expensive_brand",
        "title": "女儿要买999元球鞋",
        "role_brief": "你12岁的女儿，在班里同学都穿某品牌限量款的氛围下，认真地来跟你谈为什么她需要这双鞋",
        "tension_brief": "直接说贵不买，她会觉得你不理解；全盘答应又助长攀比风气",
        "user_goal_brief": "听完她的逻辑，给出一个有原则的回应，不伤感情",
        "primary_skills": ["L1", "E2", "B1"],
        "difficulty": 3,
        "applicable_roles": ["general"],
        "generation_prompt": "生成12岁女儿列出充足理由要求父母买贵价球鞋的开场",
    },
    {
        "category": "family",
        "sub_type": "siblings_fight_arbitrate",
        "title": "兄妹吵架要你来评判",
        "role_brief": "14岁儿子和12岁女儿，因为争夺家里某个资源（iPad使用时间/电视遥控器/出行方案选择）吵起来，都跑来找你",
        "tension_brief": "帮任何一方都伤另一方，和稀泥两边都不满意",
        "user_goal_brief": "引导他们自己谈出方案，不做裁判做调解人",
        "primary_skills": ["R1", "L1", "EM1"],
        "difficulty": 3,
        "applicable_roles": ["general"],
        "generation_prompt": "生成兄妹两人同时向你诉说对方不对、各有道理的开场",
    },
    {
        "category": "family",
        "sub_type": "parenting_disagreement",
        "title": "夫妻俩教育理念不一致",
        "role_brief": "你的伴侣，认为你对孩子管得太严（或太松），今晚当着孩子的面推翻了你刚才的决定，现在孩子回房间了，你们两个面对面",
        "tension_brief": "当下争这个显得家庭不和，但不说又会重复发生",
        "user_goal_brief": "不激化当场矛盾，把讨论引向以后如何达成一致的机制",
        "primary_skills": ["L1", "EM2", "E2"],
        "difficulty": 4,
        "applicable_roles": ["general"],
        "generation_prompt": "生成伴侣刚推翻你的决定后，带着'我也是为孩子好'的逻辑跟你说话的开场",
    },
    {
        "category": "family",
        "sub_type": "inlaws_parenting_interfere",
        "title": "公婆坚持用老方法管孩子",
        "role_brief": "你的公公/婆婆，认为现在的孩子教育太复杂，主张'打不打不重要、吃饱穿暖就行'，最近因为孙子/孙女的事开始频繁建议你们夫妻",
        "tension_brief": "正面反驳老人会伤感情伤夫妻关系，顺着说孩子被带偏",
        "user_goal_brief": "表达感谢的同时温和坚持自己的教育方向",
        "primary_skills": ["B1", "R1", "EM1"],
        "difficulty": 3,
        "applicable_roles": ["general"],
        "generation_prompt": "生成婆婆/公公以'我们那个年代怎么过来的'来建议你教育方式的开场",
    },
    {
        "category": "family",
        "sub_type": "school_teacher_complaint",
        "title": "老师约谈说孩子问题",
        "role_brief": "班主任，约谈你说孩子最近上课开小差/和同学有冲突/作业敷衍，语气里带着对家长的期待和隐性批评",
        "tension_brief": "当场辩解显得护短，全盘认错又觉得孩子委屈",
        "user_goal_brief": "了解清楚具体情况，和老师建立合作而不是对立关系",
        "primary_skills": ["L1", "E1", "EM1"],
        "difficulty": 3,
        "applicable_roles": ["general"],
        "generation_prompt": "生成班主任约谈时指出孩子问题、言下之意是家长没做好的开场",
    },
    {
        "category": "family",
        "sub_type": "partner_neglected",
        "title": "伴侣抱怨你不顾家",
        "role_brief": "你的伴侣，已经忍了很久，今晚开口说'你有没有想过这个家没你也能转'，情绪里有委屈、失望和愤怒",
        "tension_brief": "急着解释自己多忙会激化，沉默会被当作认错或无所谓",
        "user_goal_brief": "先真正接住这份委屈，再找到改变的切入点",
        "primary_skills": ["EM2", "L1", "E2"],
        "difficulty": 5,
        "applicable_roles": ["general"],
        "generation_prompt": "生成伴侣情绪爆发说出'这个家没你也能转'的开场，带着长期积累的委屈",
    },

    # ============ 朋友圈：两个角色都适用 ============
    {
        "category": "social",
        "sub_type": "gathering_showing_off",
        "title": "老同学聚会炫富攀比",
        "role_brief": "多年不见的老同学，整场聚会都在聊自己最近买的车、海外旅游和孩子读的国际学校，不时问你'你最近怎么样'",
        "tension_brief": "跟着聊就入套了，不回应又显得自卑或没格调",
        "user_goal_brief": "轻松接住而不是回避，保持自我状态，不被带节奏",
        "primary_skills": ["H1", "R1", "E1"],
        "difficulty": 3,
        "applicable_roles": ["general"],
        "generation_prompt": "生成聚会上爱炫耀的老同学主动问你近况、背后带着比较意味的开场",
    },
    {
        "category": "social",
        "sub_type": "friend_selling_insurance",
        "title": "老朋友向你推销保险",
        "role_brief": "关系不错的老朋友，最近转行做保险，约你吃饭后开始认真介绍产品，用感情牌——'我就第一个来找你，因为我觉得你需要这个保障'",
        "tension_brief": "不买伤感情，买了不合适，拖着不答复又很尴尬",
        "user_goal_brief": "明确拒绝但不伤友情，让对方知道你理解他的处境",
        "primary_skills": ["B1", "EM1", "H1"],
        "difficulty": 3,
        "applicable_roles": ["general"],
        "generation_prompt": "生成老朋友饭后拿出产品手册、用情感打动你购买意愿的开场",
    },
    {
        "category": "social",
        "sub_type": "sudden_warm_friend",
        "title": "久未联系的人突然亲热",
        "role_brief": "两年没联系的前同事/老朋友，突然发来微信嘘寒问暖，说了几句话后开始聊'最近有个事想请你帮个忙'",
        "tension_brief": "直接问什么事显得不近人情，等他说完再拒绝成本更高",
        "user_goal_brief": "自然引出对方的来意，同时为自己保留回旋余地",
        "primary_skills": ["H2", "R1", "E1"],
        "difficulty": 3,
        "applicable_roles": ["general"],
        "generation_prompt": "生成久未联系的人突然热情问候、话锋即将转向请求的开场",
    },
    {
        "category": "social",
        "sub_type": "wechat_group_awkward",
        "title": "群聊发了消息没人理",
        "role_brief": "一个平时活跃的朋友群，你分享了一件事或提了一个问题，等了半小时，群里没有任何回应，然后有人聊起了别的话题",
        "tension_brief": "追问显得没自信，就这么过去又有点尴尬",
        "user_goal_brief": "不尴尬地接住这个局面，甚至把氛围带起来",
        "primary_skills": ["H1", "H2", "E1"],
        "difficulty": 3,
        "applicable_roles": ["general"],
        "generation_prompt": "生成群聊里你的消息被忽略、其他人开始聊别的话题的场景开场",
    },
    {
        "category": "social",
        "sub_type": "friend_chicken_parenting",
        "title": "朋友阴阳怪气说你鸡娃",
        "role_brief": "相处多年的朋友，不赞同你给孩子报很多课外班，今天当着其他几个朋友的面说'哎你这也太卷了，孩子多可怜'",
        "tension_brief": "认真回应显得太在意，笑笑过去又感觉自己被否定",
        "user_goal_brief": "轻松化解，不陷入辩解，维持朋友间的和气",
        "primary_skills": ["H1", "R1", "B1"],
        "difficulty": 3,
        "applicable_roles": ["general"],
        "generation_prompt": "生成朋友当众对你的育儿方式发表阴阳评论、其他人等着看你怎么回的开场",
    },
    {
        "category": "social",
        "sub_type": "friend_divorce_advice",
        "title": "朋友倾诉婚姻危机要建议",
        "role_brief": "关系很好的朋友，约你喝茶，说出了自己婚姻里的困境（长期冷战/出轨疑虑/想离婚），希望你给出建议",
        "tension_brief": "给太具体的建议你要承担后果，不给显得冷漠，说错一句可能影响友情",
        "user_goal_brief": "真正陪伴对方梳理，而不是简单给答案或逃避",
        "primary_skills": ["EM2", "L1", "E2"],
        "difficulty": 4,
        "applicable_roles": ["general"],
        "generation_prompt": "生成朋友喝茶时犹豫地开口说婚姻里有些事撑不下去了的开场",
    },
]


def to_db_dicts() -> list[dict]:
    out = []
    for s in SCENARIOS_SEED:
        d = dict(s)
        d["primary_skills"] = json.dumps(s["primary_skills"], ensure_ascii=False)
        d["applicable_roles"] = json.dumps(s["applicable_roles"], ensure_ascii=False)
        out.append(d)
    return out
