"""场景模板种子数据 — 角色化版本（57个场景）

角色分类：
  property_manager — 物业项目经理（政府机关办公楼，管保安/保洁/会务，对接后勤处）
  decoration_boss  — 装修公司老板（管工头/工人，对接客户供应商）
  general          — 两个角色都适用（家庭 + 朋友圈场景）

场景分布：
  物业项目经理 15 个 | 装修公司老板 16 个 | 家庭 16 个 | 朋友圈 10 个
"""

import json

SCENARIOS_SEED = [
    # ============ 职场A：物业项目经理（政府机关办公楼） ============
    {
        "category": "workplace",
        "sub_type": "pm_client_extra_work",
        "title": "后勤处要求加活不加钱",
        "role_brief": "机关后勤处李主任，验收时突然提出要在原合同范围外加几项服务（增加绿化养护范围/加装监控/增加会议保障次数），态度理所当然，暗示不做就影响年底续签",
        "tension_brief": "做了亏钱亏人，不做对方卡你续签——还要把这个关系维护好",
        "user_goal_brief": "争取补偿或合理边界，不撕破脸皮，保住续签",
        "primary_skills": ["B1", "E1", "L2"],
        "difficulty": 4,
        "applicable_roles": ["property_manager"],
        "generation_prompt": "生成机关后勤处主任在验收现场要求增加合同外服务、暗示不做影响续签的开场",
    },
    {
        "category": "workplace",
        "sub_type": "pm_client_overdue_payment",
        "title": "机关拖款已3个月",
        "role_brief": "机关财务科张科长，每次催款都推说走流程、领导出差、资金还没批下来，态度客气但就是不付",
        "tension_brief": "关系不能搞僵还要继续合作，但再不催就真烂账了",
        "user_goal_brief": "逼出一个明确的打款时间节点，同时保全双方脸面",
        "primary_skills": ["B1", "R1", "E1"],
        "difficulty": 4,
        "applicable_roles": ["property_manager"],
        "generation_prompt": "生成机关财务科接到催款电话后，用'正在走审批流程'应付的场景开场",
    },
    {
        "category": "workplace",
        "sub_type": "pm_guard_visitor_conflict",
        "title": "保安和来访群众起冲突",
        "role_brief": "保安老赵，拦住一个不愿意登记身份信息的来访群众，两人争执起来，群众开始大喊大叫说要投诉，保安也上头了语气越来越冲",
        "tension_brief": "不管就升级成事件，管得不好后勤处追你责，群众也可能网上曝光",
        "user_goal_brief": "当场化解冲突，让群众配合登记，同时安抚保安情绪",
        "primary_skills": ["R1", "EM1", "L1"],
        "difficulty": 4,
        "applicable_roles": ["property_manager"],
        "generation_prompt": "生成机关门口保安和来访群众争执、声音越来越大引来越来越多人围观的场景开场",
    },
    {
        "category": "workplace",
        "sub_type": "pm_cleaner_passive",
        "title": "保洁消极怠工被后勤处点名",
        "role_brief": "做了五年的保洁大姐，最近因为工资没涨开始阳奉阴违，领导办公室卫生检查不达标，后勤处已经点了你的名",
        "tension_brief": "她走了一时找不到人，但她待着也在拖整体水平，后勤处已经在催整改",
        "user_goal_brief": "搞清楚真实诉求，找到解决方案，稳住队伍同时给后勤处交代",
        "primary_skills": ["L1", "EM1", "E2"],
        "difficulty": 3,
        "applicable_roles": ["property_manager"],
        "generation_prompt": "生成保洁大姐被约谈时，先诉苦工资低再说自己已经很努力的开场",
    },
    {
        "category": "workplace",
        "sub_type": "pm_budget_cut",
        "title": "后勤处突然要砍预算20%",
        "role_brief": "机关后勤处分管领导，开季度会时突然宣布要压缩物业管理费，理由是机关经费紧缩，态度是这是上面的决定，不讨论",
        "tension_brief": "砍了20%实际运营根本跑不动，但正面刚又显得不识好歹",
        "user_goal_brief": "用数据和逻辑争取合理预算，至少保住核心项目不被砍",
        "primary_skills": ["L2", "E1", "B1"],
        "difficulty": 5,
        "applicable_roles": ["property_manager"],
        "generation_prompt": "生成后勤处领导在会议上宣布削减物业费、强调这是上级决定的开场",
    },
    {
        "category": "workplace",
        "sub_type": "pm_client_scheme_change",
        "title": "后勤处验收前临时改方案",
        "role_brief": "后勤处项目负责人，在验收前两天突然说要调整某区域的管理方案，理由是'领导要求'，没有书面依据",
        "tension_brief": "改了要加钱加人，不改后勤处不满意签字拖",
        "user_goal_brief": "搞清楚改的范围，签补充协议，不白干活",
        "primary_skills": ["E1", "B1", "L2"],
        "difficulty": 4,
        "applicable_roles": ["property_manager"],
        "generation_prompt": "生成后勤处项目负责人提出临时变更要求、措辞含糊的开场",
    },
    {
        "category": "workplace",
        "sub_type": "pm_drinking_pressure",
        "title": "机关饭局被领导强行敬酒",
        "role_brief": "机关某位领导，在年终/节日聚餐时以'大家都喝了就你不喝显得见外'为由反复敬酒，旁边几位科长也在起哄",
        "tension_brief": "喝了身体吃不消，不喝被说没诚意，关系还要维护",
        "user_goal_brief": "优雅拒绝不失礼，找到既照顾双方脸面又不伤身体的方式",
        "primary_skills": ["H1", "B1", "R1"],
        "difficulty": 3,
        "applicable_roles": ["property_manager"],
        "generation_prompt": "生成机关饭局上领导执意敬酒、旁边人也在起哄的开场",
    },
    {
        "category": "workplace",
        "sub_type": "pm_inspection_prep",
        "title": "省领导下周来视察要求全面整改",
        "role_brief": "后勤处主任，紧急召集你开会，说省领导下周要来视察，要求三天内所有卫生、绿化、秩序全面达标，还加了几项额外准备工作",
        "tension_brief": "三天要干一周的活，人手不够请临时工来不及，做不到位就是你的责任",
        "user_goal_brief": "争取合理时间和资源，分清轻重缓急，把最关键的部分做到位",
        "primary_skills": ["L2", "E1", "R1"],
        "difficulty": 4,
        "applicable_roles": ["property_manager"],
        "generation_prompt": "生成后勤处主任紧急传达省领导视察通知、要求三天内全面整改的开场",
    },
    {
        "category": "workplace",
        "sub_type": "pm_conference_ac_broken",
        "title": "重要会议中途空调坏了",
        "role_brief": "会议室里正在开机关领导班子会议，空调突然停了，七月的天气室内温度迅速升高，后勤处副科长紧急打电话给你",
        "tension_brief": "领导在场不能出纰漏，修不好要追责，维修工说至少要两个小时",
        "user_goal_brief": "快速应变处理，安抚在场人员，找到临时解决方案",
        "primary_skills": ["R1", "E1", "L2"],
        "difficulty": 4,
        "applicable_roles": ["property_manager"],
        "generation_prompt": "生成会议中途空调坏了、后勤处的人急电你赶过来的场景开场",
    },
    {
        "category": "workplace",
        "sub_type": "pm_petition_crowd",
        "title": "信访人员在机关门口聚集",
        "role_brief": "一群约十几个信访群众，在机关大门口拉横幅/聚集喊口号，保安已经上前但明显控制不住，有人在拍视频",
        "tension_brief": "物业不是执法部门不能强制，但维持秩序是你的职责，处理不好就上新闻",
        "user_goal_brief": "配合机关信访办稳住局面，不激化矛盾，维护机关正常办公秩序",
        "primary_skills": ["EM1", "R1", "B1"],
        "difficulty": 5,
        "applicable_roles": ["property_manager"],
        "generation_prompt": "生成信访群众在机关门口聚集、保安试图劝阻但人数越来越多的场景开场",
    },
    {
        "category": "workplace",
        "sub_type": "pm_cleaner_broke_item",
        "title": "保洁打翻了领导办公室的东西",
        "role_brief": "保洁小刘，在打扫某位领导办公室时不小心碰倒了桌上的重要文件/茶具，领导当场发脾气说要换人，小刘吓哭了来找你",
        "tension_brief": "领导那边要交代，保洁这边要安抚，处理不好两头不讨好",
        "user_goal_brief": "先稳住保洁，再跟领导赔礼道歉挽回局面，保住小刘的工作",
        "primary_skills": ["EM1", "E1", "R1"],
        "difficulty": 3,
        "applicable_roles": ["property_manager"],
        "generation_prompt": "生成保洁员哭着来找你、说打翻了领导东西被骂的场景开场",
    },
    {
        "category": "workplace",
        "sub_type": "pm_new_leader_style",
        "title": "机关新领导上任服务要求全变",
        "role_brief": "新调来的机关一把手，风格和前任完全不同，对物业提出了全新的服务标准（增加巡查次数/改了会务流程/要求保安换制服），后勤处传达给你要求两周内改过来",
        "tension_brief": "改了要加钱加人，不改新领导不满意影响续签，前任领导确认过的标准全不算了",
        "user_goal_brief": "评估哪些能快速改、哪些需要资源和时间，和后勤处谈出一个可执行方案",
        "primary_skills": ["L2", "E1", "B1"],
        "difficulty": 4,
        "applicable_roles": ["property_manager"],
        "generation_prompt": "生成后勤处主任传达新领导要求、列出一系列改动清单、时间要求紧迫的开场",
    },
    {
        "category": "workplace",
        "sub_type": "pm_city_inspection",
        "title": "创建文明城市迎检突击整改",
        "role_brief": "区创文办工作人员，通知说后天要来检查，列了一份整改清单（绿化带杂物/停车秩序/楼道卫生/垃圾分类），要求明天全部到位",
        "tension_brief": "清单上的项目涉及整个大院，人力不够，做不到位会影响机关的创文考核",
        "user_goal_brief": "合理调配人手，把重点项做到位，对做不到的提前沟通而不是硬扛",
        "primary_skills": ["L2", "E1", "R1"],
        "difficulty": 3,
        "applicable_roles": ["property_manager"],
        "generation_prompt": "生成区创文办工作人员带着检查清单来传达整改要求、语气不容商量的开场",
    },
    {
        "category": "workplace",
        "sub_type": "pm_conference_service_criticized",
        "title": "会务服务员被领导当众批评",
        "role_brief": "会务服务员小陈，在一场重要会议上因为茶水倒错了顺序（先倒了陪同后倒了主客），被领导当着参会人员的面说'你们物业怎么培训的'，会议结束后小陈委屈地来找你",
        "tension_brief": "领导面子受损追你责，服务员委屈要辞职，其他会务人员也紧张了",
        "user_goal_brief": "安抚小陈的同时制定改进方案，给领导一个满意的交代",
        "primary_skills": ["EM1", "L1", "E2"],
        "difficulty": 3,
        "applicable_roles": ["property_manager"],
        "generation_prompt": "生成会务服务员小陈红着眼眶来找你、讲述被当众批评经过的场景开场",
    },
    {
        "category": "workplace",
        "sub_type": "pm_missing_item_suspect",
        "title": "机关人员遗失物品怀疑物业",
        "role_brief": "机关某科室科长，发现办公桌上的一台笔记本电脑不见了，调了监控发现只有保洁人员在他不在时进过办公室，已经报告了后勤处要求彻查",
        "tension_brief": "可能是他自己带走了记不清，但不能直接这样说，物业人员被怀疑士气受影响",
        "user_goal_brief": "配合调查的同时保护员工声誉，搞清事实真相",
        "primary_skills": ["L2", "E1", "B1"],
        "difficulty": 4,
        "applicable_roles": ["property_manager"],
        "generation_prompt": "生成机关科长气势汹汹来找你、说丢了东西怀疑是保洁拿的开场",
    },

    # ============ 职场B：装修公司老板 ============
    {
        "category": "workplace",
        "sub_type": "deco_client_redesign",
        "title": "客户反复改设计不加钱",
        "role_brief": "签了全包合同的客户，已经让你改了第三版设计稿，每次改完还有新想法，理由是'就微调一下'",
        "tension_brief": "改一次就亏一次工时，拒绝又怕客户差评，还在施工中途",
        "user_goal_brief": "温和但坚定地把边界说清楚，启动变更费收费机制",
        "primary_skills": ["B1", "E1", "R1"],
        "difficulty": 4,
        "applicable_roles": ["decoration_boss"],
        "generation_prompt": "生成客户发来第三版修改意见、依然认为是小改动的开场",
    },
    {
        "category": "workplace",
        "sub_type": "deco_client_final_payment",
        "title": "验收时客户挑刺拒付尾款",
        "role_brief": "验收当天的客户，绕着房间找问题，说墙角缝隙大了、颜色不对、地板有声音，要求全部返工再谈付款",
        "tension_brief": "有些确实是正常施工误差，但有些客户明显在找借口拖尾款",
        "user_goal_brief": "专业回应每个问题，分清合理要求和借口，争取尽快收尾款",
        "primary_skills": ["L2", "E1", "B1"],
        "difficulty": 5,
        "applicable_roles": ["decoration_boss"],
        "generation_prompt": "生成客户在验收时挑出一堆问题、强调付完尾款才算验收的开场",
    },
    {
        "category": "workplace",
        "sub_type": "deco_foreman_extra_money",
        "title": "工头工期延误还要加钱",
        "role_brief": "合作多年的工头老张，工期已经拖了10天，现在说材料涨价人工贵了，要额外加3万才继续干",
        "tension_brief": "换人更延误客户那边压力更大，不加钱工头甩手不干",
        "user_goal_brief": "谈出一个折中方案，不白给钱，也稳住工头把活收完",
        "primary_skills": ["B1", "L1", "E1"],
        "difficulty": 4,
        "applicable_roles": ["decoration_boss"],
        "generation_prompt": "生成工头老张拿着账单来你办公室，边算钱边说自己也亏了的开场",
    },
    {
        "category": "workplace",
        "sub_type": "deco_workers_fight",
        "title": "工地工人打架影响工期",
        "role_brief": "工地上两组工人——瓦工和木工——因为施工顺序问题起了冲突，有人动手，现在都停工等你来处理",
        "tension_brief": "不处理好就停工，但哪边说重了都可能有人甩手走人",
        "user_goal_brief": "当场平息，划清责任，让两组都回去干活",
        "primary_skills": ["EM1", "R1", "L1"],
        "difficulty": 4,
        "applicable_roles": ["decoration_boss"],
        "generation_prompt": "生成工地两组工人都在向你诉说对方过错、场面混乱的开场",
    },
    {
        "category": "workplace",
        "sub_type": "deco_supplier_price_hike",
        "title": "供应商突然涨价10%",
        "role_brief": "长期合作的主材供应商，微信发来通知说原材料涨价，下周起所有订单涨10%，已签合同也要补差价",
        "tension_brief": "已签给客户的价格改不了，吃下去直接亏，但找新供应商也来不及",
        "user_goal_brief": "谈出保价方案或分摊机制，不能全部自己扛",
        "primary_skills": ["B1", "E1", "L2"],
        "difficulty": 4,
        "applicable_roles": ["decoration_boss"],
        "generation_prompt": "生成供应商发来涨价通知、强调成本压力的开场",
    },
    {
        "category": "workplace",
        "sub_type": "deco_client_night_msg",
        "title": "客户深夜连发消息催进度",
        "role_brief": "焦虑型客户，晚上11点开始在微信群发消息，说明天要来看进度、要求解释为什么还没贴砖，@了你和工头",
        "tension_brief": "睡着了没回会被认为不负责，回了又给自己立了随时待命的规矩",
        "user_goal_brief": "回应关切但设定沟通边界，明确进度节点，不让深夜骚扰成常态",
        "primary_skills": ["B1", "R1", "E1"],
        "difficulty": 3,
        "applicable_roles": ["decoration_boss"],
        "generation_prompt": "生成客户深夜在微信群发消息连问几个问题的开场",
    },
    {
        "category": "workplace",
        "sub_type": "deco_complaint_12345",
        "title": "接到12345转来的投诉",
        "role_brief": "当地市场监管部门工作人员，转达了某客户的投诉（说你们施工噪音扰民/材料以次充好），要求你在3个工作日内书面回复",
        "tension_brief": "这个客户确实有纠纷在处理，但部门介入升级了压力",
        "user_goal_brief": "妥善处理投诉，避免被列入黑名单，同时推动客户纠纷解决",
        "primary_skills": ["L2", "E1", "R1"],
        "difficulty": 3,
        "applicable_roles": ["decoration_boss"],
        "generation_prompt": "生成监管部门工作人员电话通知投诉情况、语气公事公办的开场",
    },
    {
        "category": "workplace",
        "sub_type": "deco_old_client_discount",
        "title": "老客户要求熟人价折扣",
        "role_brief": "三年前装过房的老客户，帮你介绍了两个新客户，现在自己想装第二套房，理由充分地要求8折",
        "tension_brief": "8折直接亏本，但老客户介绍过生意，驳了他面子也影响口碑",
        "user_goal_brief": "感谢老客户的同时，婉拒过分折扣，给出一个双方都能接受的方案",
        "primary_skills": ["H1", "B1", "R1"],
        "difficulty": 3,
        "applicable_roles": ["decoration_boss"],
        "generation_prompt": "生成老客户理直气壮地要8折、历数自己之前贡献的开场",
    },
    {
        "category": "workplace",
        "sub_type": "deco_chase_payment",
        "title": "追业主付工程款拖了两个月",
        "role_brief": "业主王哥，装修完工一个月了还有40%尾款没付，电话不接微信不回，好不容易打通了说手头紧再等等",
        "tension_brief": "你这边材料费工钱都要结，他的钱不到位你就得垫，但逼太紧怕他挑毛病",
        "user_goal_brief": "逼出一个明确的付款时间，不伤和气但也不能再拖",
        "primary_skills": ["B1", "E1", "R1"],
        "difficulty": 4,
        "applicable_roles": ["decoration_boss"],
        "generation_prompt": "生成业主接到催款电话、开始找各种理由推脱的场景开场",
    },
    {
        "category": "workplace",
        "sub_type": "deco_client_price_compare",
        "title": "业主拿别家报价来压价",
        "role_brief": "正在谈方案的准客户，拿出另一家装修公司的报价单，说人家同样户型才多少多少钱，问你能不能做到这个价",
        "tension_brief": "跟着降价就亏，不降客户可能真走了，而且那个报价多半是减配的",
        "user_goal_brief": "不陷入价格战，让客户理解差异在哪里，保住合理利润",
        "primary_skills": ["L2", "E1", "R1"],
        "difficulty": 3,
        "applicable_roles": ["decoration_boss"],
        "generation_prompt": "生成准客户拿着别家报价单、用'你看看人家这个价'来压你降价的场景开场",
    },
    {
        "category": "workplace",
        "sub_type": "deco_hidden_problem_extra_cost",
        "title": "施工发现隐蔽问题要加钱",
        "role_brief": "业主，拆墙后发现墙体内部有严重的渗水发霉，必须额外处理防水层，你报价加了8000元，业主觉得你是故意找借口多收钱",
        "tension_brief": "不处理后面出了问题更麻烦，但业主不信任你认为是坑他",
        "user_goal_brief": "让业主理解这不是你加的价而是房子本身的问题，促成合理方案",
        "primary_skills": ["L2", "E1", "EM1"],
        "difficulty": 4,
        "applicable_roles": ["decoration_boss"],
        "generation_prompt": "生成业主看着拆开的墙面、质疑你是不是故意夸大问题来多收费的场景开场",
    },
    {
        "category": "workplace",
        "sub_type": "deco_neighbor_complaint",
        "title": "楼下邻居投诉噪音堵工地门",
        "role_brief": "楼下邻居，因为装修噪音/粉尘问题已经投诉过两次了，今天直接堵在工地门口不让人进去干活，说要找物业和城管",
        "tension_brief": "工期本来就紧，停一天亏一天，但邻居确实被影响了，闹大了城管来停工更麻烦",
        "user_goal_brief": "安抚邻居情绪，调整施工方案减少影响，保住工期",
        "primary_skills": ["EM1", "R1", "E1"],
        "difficulty": 3,
        "applicable_roles": ["decoration_boss"],
        "generation_prompt": "生成楼下邻居堵在工地门口、情绪激动地说受够了噪音的场景开场",
    },
    {
        "category": "workplace",
        "sub_type": "deco_worker_cutting_corners",
        "title": "工人偷工减料被业主发现",
        "role_brief": "业主，验收时发现某个角落的材料跟合同约定不一致（用了便宜材料/少了一道工序），拿着合同来跟你算账，语气很不好",
        "tension_brief": "你确实不知情是工人私下换的，但业主找的是你，认了赔钱不认丢客户",
        "user_goal_brief": "承认问题承担责任，给出补救方案，挽回信任",
        "primary_skills": ["E1", "EM1", "B1"],
        "difficulty": 4,
        "applicable_roles": ["decoration_boss"],
        "generation_prompt": "生成业主拿着合同和实际材料对比、质疑你是不是在坑他的场景开场",
    },
    {
        "category": "workplace",
        "sub_type": "deco_year_end_collection",
        "title": "年底三个业主同时欠款要催收",
        "role_brief": "年底了，三个不同项目的业主都拖着尾款不付，理由各不相同（资金紧张/还在验/觉得有问题），你的工人们等着拿钱回家过年",
        "tension_brief": "工人拿不到钱会闹，业主不给钱你没法结算，年底时间紧迫",
        "user_goal_brief": "分清哪个能催动哪个要放一放，先解决最急的，不给工人留话柄",
        "primary_skills": ["L2", "E1", "B1"],
        "difficulty": 5,
        "applicable_roles": ["decoration_boss"],
        "generation_prompt": "生成年底工人来催工资、而三个业主都在拖尾款的场景开场",
    },
    {
        "category": "workplace",
        "sub_type": "deco_foreman_poached",
        "title": "同行高价挖你的工头",
        "role_brief": "跟了你五年的工头老张，被竞争对手加了20%的价挖走，他犹豫着来找你说想走，但又觉得对不起你这些年的照顾",
        "tension_brief": "他走了带走几个工人，手头三个项目工期都受影响，但硬留也留不住心",
        "user_goal_brief": "不卑不亢地谈，要么留人要么争取一个缓冲期把手里项目交接完",
        "primary_skills": ["EM1", "E1", "B1"],
        "difficulty": 4,
        "applicable_roles": ["decoration_boss"],
        "generation_prompt": "生成工头老张犹豫地来找你、吞吞吐吐说有人在挖他的场景开场",
    },
    {
        "category": "workplace",
        "sub_type": "deco_client_group_rant",
        "title": "客户在装修群里语音骂人",
        "role_brief": "业主，在一个有其他业主推荐的微信群里发语音骂你们公司施工质量差、不负责，群里还有几个你的潜在客户在观望",
        "tension_brief": "不当场回应损失扩大，回应得太硬气又显得态度差，潜在客户会跑",
        "user_goal_brief": "专业冷静地回应，把问题从公共群引到私下沟通，同时让其他群友看到你的态度",
        "primary_skills": ["R1", "E1", "H1"],
        "difficulty": 4,
        "applicable_roles": ["decoration_boss"],
        "generation_prompt": "生成业主在微信群里连发几条语音骂人、群里其他人在看的场景开场",
    },

    # ============ 家庭：两个角色都适用 ============
    {
        "category": "family",
        "sub_type": "teen_son_backtalk",
        "title": "14岁儿子顶嘴不服管",
        "role_brief": "你14岁的儿子，因为被要求少打游戏多看书，开始顶嘴，说'你也不看书，凭什么管我'",
        "tension_brief": "大声压制他会让他更对抗，无视他又助长这种态度",
        "user_goal_brief": "不硬碰硬，把对话引向真正的问题——他为什么抵触学习",
        "primary_skills": ["L1", "EM1", "E2"],
        "difficulty": 4,
        "applicable_roles": ["general"],
        "generation_prompt": "生成14岁少年被要求放下手机、用反问句顶嘴的开场",
    },
    {
        "category": "family",
        "sub_type": "teen_son_study_useless",
        "title": "儿子说读书没什么用",
        "role_brief": "你14岁的儿子，看了某个视频说某网红学历低但收入高，现在跟你认真地讨论读书到底有没有用",
        "tension_brief": "用老一套大道理他不信，但真的允许他这么想又危险",
        "user_goal_brief": "认真回应而不是敷衍，帮他建立更有深度的思考框架",
        "primary_skills": ["L1", "H1", "E2"],
        "difficulty": 4,
        "applicable_roles": ["general"],
        "generation_prompt": "生成14岁儿子认真提出'读书无用论'、并举了真实例子的开场",
    },
    {
        "category": "family",
        "sub_type": "teen_son_gaming_addict",
        "title": "儿子熬夜打游戏到凌晨2点",
        "role_brief": "你14岁的儿子，被你发现又熬夜打游戏，承认了但辩解说反正明天不上课、他能控制自己",
        "tension_brief": "骂了当晚收一下，明天继续；讲道理他右耳进左耳出",
        "user_goal_brief": "找到让他自己认识到问题的方式，而不只是一次性说服",
        "primary_skills": ["EM1", "L1", "E2"],
        "difficulty": 3,
        "applicable_roles": ["general"],
        "generation_prompt": "生成凌晨被发现打游戏的儿子，不太在乎地辩解自己能控制的开场",
    },
    {
        "category": "family",
        "sub_type": "daughter_social_excluded",
        "title": "12岁女儿说被同学孤立",
        "role_brief": "你12岁的女儿，哭着告诉你班里几个好朋友突然不理她了，她不知道为什么，觉得自己做错了什么",
        "tension_brief": "直接给建议容易让她觉得不被理解，光安慰又没用",
        "user_goal_brief": "先接住她的情绪，再帮她梳理发生了什么，找到她能做的第一步",
        "primary_skills": ["EM2", "L1", "E2"],
        "difficulty": 3,
        "applicable_roles": ["general"],
        "generation_prompt": "生成12岁女儿哭泣着说被好朋友冷落、不知道原因的开场",
    },
    {
        "category": "family",
        "sub_type": "daughter_expensive_brand",
        "title": "女儿要买999元球鞋",
        "role_brief": "你12岁的女儿，在班里同学都穿某品牌限量款的氛围下，认真地来跟你谈为什么她需要这双鞋",
        "tension_brief": "直接说贵不买，她会觉得你不理解；全盘答应又助长攀比风气",
        "user_goal_brief": "听完她的逻辑，给出一个有原则的回应，不伤感情",
        "primary_skills": ["L1", "E2", "B1"],
        "difficulty": 3,
        "applicable_roles": ["general"],
        "generation_prompt": "生成12岁女儿列出充足理由要求父母买贵价球鞋的开场",
    },
    {
        "category": "family",
        "sub_type": "siblings_fight_arbitrate",
        "title": "兄妹吵架要你来评判",
        "role_brief": "14岁儿子和12岁女儿，因为争夺家里某个资源（iPad使用时间/电视遥控器/出行方案选择）吵起来，都跑来找你",
        "tension_brief": "帮任何一方都伤另一方，和稀泥两边都不满意",
        "user_goal_brief": "引导他们自己谈出方案，不做裁判做调解人",
        "primary_skills": ["R1", "L1", "EM1"],
        "difficulty": 3,
        "applicable_roles": ["general"],
        "generation_prompt": "生成兄妹两人同时向你诉说对方不对、各有道理的开场",
    },
    {
        "category": "family",
        "sub_type": "parenting_disagreement",
        "title": "夫妻俩教育理念不一致",
        "role_brief": "你的伴侣，认为你对孩子管得太严（或太松），今晚当着孩子的面推翻了你刚才的决定，现在孩子回房间了，你们两个面对面",
        "tension_brief": "当下争这个显得家庭不和，但不说又会重复发生",
        "user_goal_brief": "不激化当场矛盾，把讨论引向以后如何达成一致的机制",
        "primary_skills": ["L1", "EM2", "E2"],
        "difficulty": 4,
        "applicable_roles": ["general"],
        "generation_prompt": "生成伴侣刚推翻你的决定后，带着'我也是为孩子好'的逻辑跟你说话的开场",
    },
    {
        "category": "family",
        "sub_type": "inlaws_parenting_interfere",
        "title": "公婆坚持用老方法管孩子",
        "role_brief": "你的公公/婆婆，认为现在的孩子教育太复杂，主张'打不打不重要、吃饱穿暖就行'，最近因为孙子/孙女的事开始频繁建议你们夫妻",
        "tension_brief": "正面反驳老人会伤感情伤夫妻关系，顺着说孩子被带偏",
        "user_goal_brief": "表达感谢的同时温和坚持自己的教育方向",
        "primary_skills": ["B1", "R1", "EM1"],
        "difficulty": 3,
        "applicable_roles": ["general"],
        "generation_prompt": "生成婆婆/公公以'我们那个年代怎么过来的'来建议你教育方式的开场",
    },
    {
        "category": "family",
        "sub_type": "school_teacher_complaint",
        "title": "老师约谈说孩子问题",
        "role_brief": "班主任，约谈你说孩子最近上课开小差/和同学有冲突/作业敷衍，语气里带着对家长的期待和隐性批评",
        "tension_brief": "当场辩解显得护短，全盘认错又觉得孩子委屈",
        "user_goal_brief": "了解清楚具体情况，和老师建立合作而不是对立关系",
        "primary_skills": ["L1", "E1", "EM1"],
        "difficulty": 3,
        "applicable_roles": ["general"],
        "generation_prompt": "生成班主任约谈时指出孩子问题、言下之意是家长没做好的开场",
    },
    {
        "category": "family",
        "sub_type": "partner_neglected",
        "title": "伴侣抱怨你不顾家",
        "role_brief": "你的伴侣，已经忍了很久，今晚开口说'你有没有想过这个家没你也能转'，情绪里有委屈、失望和愤怒",
        "tension_brief": "急着解释自己多忙会激化，沉默会被当作认错或无所谓",
        "user_goal_brief": "先真正接住这份委屈，再找到改变的切入点",
        "primary_skills": ["EM2", "L1", "E2"],
        "difficulty": 5,
        "applicable_roles": ["general"],
        "generation_prompt": "生成伴侣情绪爆发说出'这个家没你也能转'的开场，带着长期积累的委屈",
    },
    {
        "category": "family",
        "sub_type": "son_secret_purchase",
        "title": "儿子偷偷充值游戏好几百",
        "role_brief": "你14岁的儿子，趁你不注意用你绑定的支付宝/微信在游戏里充值了好几百，被你发现了账单记录",
        "tension_brief": "直接骂他又会激化矛盾，但几百块钱不是小数目，而且他偷偷用你手机是信任问题",
        "user_goal_brief": "让他认识到错误并主动承担责任，同时建立家庭财务规则",
        "primary_skills": ["B1", "L1", "E2"],
        "difficulty": 3,
        "applicable_roles": ["general"],
        "generation_prompt": "生成14岁儿子被发现偷偷充值游戏后，先是否认然后找理由辩解的场景开场",
    },
    {
        "category": "family",
        "sub_type": "daughter_grades_drop",
        "title": "女儿成绩下滑不想补课",
        "role_brief": "你12岁的女儿，月考成绩出来退步明显，但你说给她报补习班她很抗拒，说'我就是学不好，别逼我了'",
        "tension_brief": "不管成绩继续掉，逼太紧她更抵触甚至厌学",
        "user_goal_brief": "找到她抗拒的真正原因，不是强迫补课而是帮她找到学习动力",
        "primary_skills": ["L1", "EM2", "E2"],
        "difficulty": 4,
        "applicable_roles": ["general"],
        "generation_prompt": "生成12岁女儿情绪低落地说自己就是学不好、不想补课的场景开场",
    },
    {
        "category": "family",
        "sub_type": "son_inappropriate_content",
        "title": "妻子发现儿子手机上不该看的东西",
        "role_brief": "你的妻子，今天趁儿子不注意翻了手机，发现了一些不适宜的浏览记录，又气又慌地来找你，问你怎么办",
        "tension_brief": "直接找儿子质问他觉得被侵犯隐私会更叛逆，不管又怕影响成长",
        "user_goal_brief": "安抚妻子情绪，商量出一个既保护孩子自尊又引导正确认知的方式",
        "primary_skills": ["EM1", "E2", "L1"],
        "difficulty": 4,
        "applicable_roles": ["general"],
        "generation_prompt": "生成妻子压低声音又急又气地来说'你来看看儿子手机上都看了什么'的场景开场",
    },
    {
        "category": "family",
        "sub_type": "spouse_work_stress_venting",
        "title": "配偶工作压力大回家冲你发火",
        "role_brief": "你的伴侣，最近项目压力很大，今天回家因为一件小事（碗没洗/孩子作业没检查）突然爆发，说'这个家全靠我一个人在撑'",
        "tension_brief": "不是你的错但气撒在你身上，怼回去会吵起来，忍着又委屈",
        "user_goal_brief": "先接住对方的情绪，找到合适的时机再沟通，不激化也不憋着",
        "primary_skills": ["EM2", "R1", "L1"],
        "difficulty": 4,
        "applicable_roles": ["general"],
        "generation_prompt": "生成伴侣回家后因为一件小事突然爆发、说出伤人话的场景开场",
    },
    {
        "category": "family",
        "sub_type": "new_year_parents_allocation",
        "title": "过年去谁父母家又吵了",
        "role_brief": "你的伴侣，又到了讨论过年去谁家的时候了，去年去了你家今年想回自己家，但你觉得你妈身体不好想多陪陪，双方都有道理但互不让步",
        "tension_brief": "两边父母都有感情和道义，年年都吵，今年谁都不想先让",
        "user_goal_brief": "不选边站，找一个双方都能接受的方案或者新思路",
        "primary_skills": ["R1", "E1", "EM1"],
        "difficulty": 3,
        "applicable_roles": ["general"],
        "generation_prompt": "生成伴侣先发制人地提出今年要回自己家过年、理由很充分的开场",
    },
    {
        "category": "family",
        "sub_type": "child_misunderstood",
        "title": "孩子说'你们根本不理解我'",
        "role_brief": "你的孩子（儿子或女儿），因为你一句关心的话（'你怎么又没考好'/'少玩点手机'）突然情绪爆发，说'你们只会管我学习/从来不问我想什么/根本不理解我'",
        "tension_brief": "你觉得自己是在关心，他觉得你在控制，辩解会让他更觉得你不理解",
        "user_goal_brief": "不急着解释自己的好意，先真正听懂他在说什么",
        "primary_skills": ["L1", "EM2", "E2"],
        "difficulty": 4,
        "applicable_roles": ["general"],
        "generation_prompt": "生成孩子突然情绪爆发、说出'你们根本不理解我'然后沉默的场景开场",
    },

    # ============ 朋友圈：两个角色都适用 ============
    {
        "category": "social",
        "sub_type": "gathering_showing_off",
        "title": "老同学聚会炫富攀比",
        "role_brief": "多年不见的老同学，整场聚会都在聊自己最近买的车、海外旅游和孩子读的国际学校，不时问你'你最近怎么样'",
        "tension_brief": "跟着聊就入套了，不回应又显得自卑或没格调",
        "user_goal_brief": "轻松接住而不是回避，保持自我状态，不被带节奏",
        "primary_skills": ["H1", "R1", "E1"],
        "difficulty": 3,
        "applicable_roles": ["general"],
        "generation_prompt": "生成聚会上爱炫耀的老同学主动问你近况、背后带着比较意味的开场",
    },
    {
        "category": "social",
        "sub_type": "friend_selling_insurance",
        "title": "老朋友向你推销保险",
        "role_brief": "关系不错的老朋友，最近转行做保险，约你吃饭后开始认真介绍产品，用感情牌——'我就第一个来找你，因为我觉得你需要这个保障'",
        "tension_brief": "不买伤感情，买了不合适，拖着不答复又很尴尬",
        "user_goal_brief": "明确拒绝但不伤友情，让对方知道你理解他的处境",
        "primary_skills": ["B1", "EM1", "H1"],
        "difficulty": 3,
        "applicable_roles": ["general"],
        "generation_prompt": "生成老朋友饭后拿出产品手册、用情感打动你购买意愿的开场",
    },
    {
        "category": "social",
        "sub_type": "sudden_warm_friend",
        "title": "久未联系的人突然亲热",
        "role_brief": "两年没联系的前同事/老朋友，突然发来微信嘘寒问暖，说了几句话后开始聊'最近有个事想请你帮个忙'",
        "tension_brief": "直接问什么事显得不近人情，等他说完再拒绝成本更高",
        "user_goal_brief": "自然引出对方的来意，同时为自己保留回旋余地",
        "primary_skills": ["H2", "R1", "E1"],
        "difficulty": 3,
        "applicable_roles": ["general"],
        "generation_prompt": "生成久未联系的人突然热情问候、话锋即将转向请求的开场",
    },
    {
        "category": "social",
        "sub_type": "wechat_group_awkward",
        "title": "群聊发了消息没人理",
        "role_brief": "一个平时活跃的朋友群，你分享了一件事或提了一个问题，等了半小时，群里没有任何回应，然后有人聊起了别的话题",
        "tension_brief": "追问显得没自信，就这么过去又有点尴尬",
        "user_goal_brief": "不尴尬地接住这个局面，甚至把氛围带起来",
        "primary_skills": ["H1", "H2", "E1"],
        "difficulty": 3,
        "applicable_roles": ["general"],
        "generation_prompt": "生成群聊里你的消息被忽略、其他人开始聊别的话题的场景开场",
    },
    {
        "category": "social",
        "sub_type": "friend_chicken_parenting",
        "title": "朋友阴阳怪气说你鸡娃",
        "role_brief": "相处多年的朋友，不赞同你给孩子报很多课外班，今天当着其他几个朋友的面说'哎你这也太卷了，孩子多可怜'",
        "tension_brief": "认真回应显得太在意，笑笑过去又感觉自己被否定",
        "user_goal_brief": "轻松化解，不陷入辩解，维持朋友间的和气",
        "primary_skills": ["H1", "R1", "B1"],
        "difficulty": 3,
        "applicable_roles": ["general"],
        "generation_prompt": "生成朋友当众对你的育儿方式发表阴阳评论、其他人等着看你怎么回的开场",
    },
    {
        "category": "social",
        "sub_type": "friend_divorce_advice",
        "title": "朋友倾诉婚姻危机要建议",
        "role_brief": "关系很好的朋友，约你喝茶，说出了自己婚姻里的困境（长期冷战/出轨疑虑/想离婚），希望你给出建议",
        "tension_brief": "给太具体的建议你要承担后果，不给显得冷漠，说错一句可能影响友情",
        "user_goal_brief": "真正陪伴对方梳理，而不是简单给答案或逃避",
        "primary_skills": ["EM2", "L1", "E2"],
        "difficulty": 4,
        "applicable_roles": ["general"],
        "generation_prompt": "生成朋友喝茶时犹豫地开口说婚姻里有些事撑不下去了的开场",
    },
    {
        "category": "social",
        "sub_type": "friend_investment_pitch",
        "title": "朋友创业拉你投资入伙",
        "role_brief": "关系不错的朋友，最近辞职创业做了个项目，约你吃饭后认真地拉你入伙或投资，说'就差你一个了''这个机会错过就没了'",
        "tension_brief": "不投伤感情，投了怕亏钱又伤感情，含糊答应也不是长久之计",
        "user_goal_brief": "认真评估但不被感情绑架，明确表态不伤友情",
        "primary_skills": ["B1", "L2", "H1"],
        "difficulty": 3,
        "applicable_roles": ["general"],
        "generation_prompt": "生成朋友热情地介绍创业项目、反复强调机会难得、暗示不投就是不信他的开场",
    },
    {
        "category": "social",
        "sub_type": "unfamiliar_dinner_party",
        "title": "被拉去不熟的饭局应酬",
        "role_brief": "一个半熟不熟的朋友，拉你去参加一个饭局，说'来都是朋友'就坐下了，结果桌上一圈人你一个都不认识，主人在逐个敬酒轮到你了",
        "tension_brief": "太拘谨显得不合群，太自来熟又尴尬，不说点什么场面冷着",
        "user_goal_brief": "自然地融入，不说场面话也不冷场，找到一个舒服的社交节奏",
        "primary_skills": ["H1", "R1", "E1"],
        "difficulty": 3,
        "applicable_roles": ["general"],
        "generation_prompt": "生成饭局上主人举杯轮到你、全桌人看着你等你说话的场景开场",
    },
    {
        "category": "social",
        "sub_type": "neighbor_parking_dispute",
        "title": "邻居停车堵了你车位",
        "role_brief": "楼上/隔壁邻居，经常停车堵在你车位或家门口，今天又堵了，你敲他门他说'就停一会儿你至于吗'",
        "tension_brief": "低头不见抬头见，不能撕但又真的很烦，每次都是停一会儿",
        "user_goal_brief": "让他意识到这不是小事，但不说重话不伤邻里关系",
        "primary_skills": ["B1", "H1", "R1"],
        "difficulty": 2,
        "applicable_roles": ["general"],
        "generation_prompt": "生成邻居不以为然地说'就停一会儿'、觉得你小题大做的场景开场",
    },
    {
        "category": "social",
        "sub_type": "friend_debt_vacation",
        "title": "欠钱的朋友发旅游照片给你",
        "role_brief": "一年前借了钱的朋友，说周转困难你借了两万，到现在一分没还，催了几次说下个月。今天他主动给你发微信聊近况，还发了旅游照片，完全没提还钱",
        "tension_brief": "直接问显得你盯着他，不问心里过不去，钱数目不小",
        "user_goal_brief": "自然地把话题引到还钱上，不伤面子但表达清楚你的态度",
        "primary_skills": ["B1", "R1", "E1"],
        "difficulty": 3,
        "applicable_roles": ["general"],
        "generation_prompt": "生成欠你钱的朋友主动发微信聊近况、发了旅游照片、完全没提还钱的场景开场",
    },
]


def to_db_dicts() -> list[dict]:
    out = []
    for s in SCENARIOS_SEED:
        d = dict(s)
        d["primary_skills"] = json.dumps(s["primary_skills"], ensure_ascii=False)
        d["applicable_roles"] = json.dumps(s["applicable_roles"], ensure_ascii=False)
        out.append(d)
    return out
